name: Build
on:
  - push
jobs:
  screenshots:
    name: Generate Screenshots
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml
          coverage: none

      - name: Prepare the environment
        run: cp .env.dev .env

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Setup npm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install npm dependencies
        run: npm install --no-progress --no-save --no-optional

      - name: Build assets
        run: npm run production

      - name: Generate application key
        run: php artisan key:generate

      - name: Create database
        run: touch database/database.sqlite

      - name: Seed database
        run: php artisan migrate:fresh --seed

      - name: Run Dusk tests
        env:
          APP_ENV: testing
          APP_URL: http://127.0.0.1:8000
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
        run: php artisan screenshot

      - name: Upload screenshots
        if: succes()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: public/images/screenshots
